### ISSUE TITLE
error in the R script of spikChIP

### ISSUE THREAD

**Issue by sgomezgonzalez** [eblancoga/spikChIP#2]
I was trying to apply the spikChIP methodology to my data and the script ended abruptly at this point:

%%%% Run local regression adjusting sample values with spike values
%%%% Performing the analysis on average values
%%%% R CMD BATCH Rscripts/1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16_10000_avg.R
%%%% R running: Error in read.table("results/1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16_SPIKCHIP_10000_spike-sample_avg_names.txt") : 

%%%% [Wed Aug 23 09:54:54 2023] Stage X.  Abruptly finishing the work
%%%% Total running time (hours): 0.578  hours
%%%% Total running time (minutes): 34.683  mins
%%%% Total running time (seconds): 2081  secs [OK]

I've looked to the table "results/1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16_SPIKCHIP_10000_spike-sample_avg_names.txt" and it is empty. 
Can you help me with this error? Thanks!

**Comment by eblancoga** [comment]
Hi!

Sure, please can you give me more details about (log file, species, chromosomes, etc.)?

Enrique

________________________________________
Dr. Enrique Blanco García (PhD)
https://sites.google.com/site/eblancog2014/
http://orcid.org/0000-0001-6261-7370

Epigenetic Events in Cancer (L. Di Croce's lab)
Gene Regulation, Stem Cells and Cancer
Centre for Genomic Regulation (CRG)
C/ Dr. Aiguader, 88
08003 Barcelona
Spain


________________________________
De: sgomezgonzalez ***@***.***>
Enviado: miércoles, 23 de agosto de 2023 10:22
Para: eblancoga/spikChIP ***@***.***>
Cc: Subscribed ***@***.***>
Asunto: [eblancoga/spikChIP] error in the R script of spikChIP (Issue #2)


I was trying to apply the spikChIP methodology to my data and the script ended abruptly at this point:

%%%% Run local regression adjusting sample values with spike values
%%%% Performing the analysis on average values
%%%% R CMD BATCH Rscripts/1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16_10000_avg.R
%%%% R running: Error in read.table("results/1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16_SPIKCHIP_10000_spike-sample_avg_names.txt") :

%%%% [Wed Aug 23 09:54:54 2023] Stage X. Abruptly finishing the work
%%%% Total running time (hours): 0.578 hours
%%%% Total running time (minutes): 34.683 mins
%%%% Total running time (seconds): 2081 secs [OK]

I've looked to the table "results/1-2-3-4-5-6-7-8-9-10-11-12-13-14-15-16_SPIKCHIP_10000_spike-sample_avg_names.txt" and it is empty.
Can you help me with this error? Thanks!

**Comment by sgomezgonzalez** [comment]
Hi! 

Thanks for your prompt reply!

I have followed the steps described in the protocol "Blanco, E., Ballaré, C., Di Croce, L., Aranda, S. (2023). Quantitative Comparison of Multiple Chromatin Immunoprecipitation-Sequencing (ChIP-seq) Experiments with spikChIP. In: Oliveira, P.H. (eds) Computational Epigenomics and Epitranscriptomics. Methods in Molecular Biology, vol 2624. Humana, New York, NY. https://doi.org/10.1007/978-1-0716-2962-8_5".

I have aligned the fastq files using bowtie to a hybrid genome, combining hg38 and dm3_FLY.

The chromosomes:
- hg38 chromosomes: 1:22,"X","Y","M"
- dm3 chromosomes: "chr2L","chr2R","chr3L","chr3R","chr4","chrX","chrM"

Attached you will find the log file.

[spikChIP.log](https://github.com/eblancoga/spikChIP/files/12418583/spikChIP.log)

Thank you very much for your help!

Soledad

**Comment by eblancoga** [comment]
Hola Soledad,

I've carefully analyzed your LOG file and I think you need to install our
JoinNFiles.pl script in your computer (or at least you need to make
it executable with chmod or export PATH commands).

You have several occurrences of this error in your LOG:
sh: 1: JoinNFiles.pl: not found

This script is included into our repository here:
https://github.com/eblancoga/spikChIP/blob/master/JoinNFiles.pl

You should be able to run it from your current PATH environment before running spikChIP.

Good luck!

Enrique


________________________________________
Dr. Enrique Blanco García (PhD)
https://sites.google.com/site/eblancog2014/
http://orcid.org/0000-0001-6261-7370

Epigenetic Events in Cancer (L. Di Croce's lab)
Gene Regulation, Stem Cells and Cancer
Centre for Genomic Regulation (CRG)
C/ Dr. Aiguader, 88
08003 Barcelona
Spain


________________________________
De: sgomezgonzalez ***@***.***>
Enviado: miércoles, 23 de agosto de 2023 13:27
Para: eblancoga/spikChIP ***@***.***>
Cc: Enrique Blanco Garcia ***@***.***>; Comment ***@***.***>
Asunto: Re: [eblancoga/spikChIP] error in the R script of spikChIP (Issue #2)


Hi!

Thanks for your prompt reply!

I have followed the steps described in the protocol "Blanco, E., Ballaré, C., Di Croce, L., Aranda, S. (2023). Quantitative Comparison of Multiple Chromatin Immunoprecipitation-Sequencing (ChIP-seq) Experiments with spikChIP. In: Oliveira, P.H. (eds) Computational Epigenomics and Epitranscriptomics. Methods in Molecular Biology, vol 2624. Humana, New York, NY. https://doi.org/10.1007/978-1-0716-2962-8_5<https://urldefense.com/v3/__https://doi.org/10.1007/978-1-0716-2962-8_5__;!!D9dNQwwGXtA!XNHCrWIRKSohajkPYh92uEQaUVwNfw_NH77dF6Yoa3WxgQTwOb248_EUPUC4eniyrtI68VyqWut5ixq-5jEu6UGMHWCD$>".

I have aligned the fastq files using bowtie to a hybrid genome, combining hg38 and dm3_FLY.

The chromosomes:

  *   hg38 chromosomes: 1:22,"X","Y","M"
  *   dm3 chromosomes: "chr2L","chr2R","chr3L","chr3R","chr4","chrX","chrM"

Attached you will find the log file.

spikChIP.log<https://urldefense.com/v3/__https://github.com/eblancoga/spikChIP/files/12418583/spikChIP.log__;!!D9dNQwwGXtA!XNHCrWIRKSohajkPYh92uEQaUVwNfw_NH77dF6Yoa3WxgQTwOb248_EUPUC4eniyrtI68VyqWut5ixq-5jEu6f9kVzSd$>

Thank you very much for your help!

Soledad
